name: Build LaTeX document
on: [push]
jobs:
  build_latex:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v2
      - name: Compile LaTeX document
        uses: dante-ev/latex-action@latest
        with:
          root_file: | 
            WS_Primo_Assignment/main.tex
            WS_Primo_Assignment/01_Introduzione.tex
      - uses: actions/upload-artifact@v2
        with:
          name: PDF
          path: main.pdf
